/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.BLL_PDP;
import DTO.DTO_PHdatphong;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Vector;
import java.util.regex.PatternSyntaxException;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
      
public class GUI_QLphieuDP extends javax.swing.JFrame {
    private String listphongtrong[];
    private TableRowSorter<TableModel> sorter;

    public void setListphongtrong(String tt) {
         listphongtrong =BLL.BLL_dodulieuPhong.listroomok(tt);
    }        


    /**
     * Creates new form GUI_QLphieuDP
     */
    public GUI_QLphieuDP() {
        setListphongtrong("Trống");
      
        initComponents();
        this.setTitle("Quản lý Đặt trả phòng");
        btnhanphong.setVisible(false);
                 bttraphong.setVisible(false);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
               
                dispose();
            }
        });
     
        
          BLL.BLL_dodulieu_PDP.dodulieu(jTable1);
          
        sorter = new TableRowSorter<TableModel>(jTable1.getModel());
        jTable1.setRowSorter(sorter);
        
        txt_timkiem.getDocument().addDocumentListener(new DocumentListener(){
        @Override
        public void insertUpdate(DocumentEvent e) {
            String text = txt_timkiem.getText();

            if (text.trim().length() == 0) {
                sorter.setRowFilter(null);
            } else {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
            }
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            String text = txt_timkiem.getText();

            if (text.trim().length() == 0) {
                sorter.setRowFilter(null);
            } else {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
            }
        }

        @Override
        public void changedUpdate(DocumentEvent e) {

        }

    });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_userkh = new javax.swing.JTextField();
        txt_datet = new javax.swing.JTextField();
        txt_ndate = new javax.swing.JTextField();
        txt_room = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_namekh = new javax.swing.JTextField();
        txt_old = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_cmnd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_gt = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ttang = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        bt_save = new javax.swing.JButton();
        bt_delete1 = new javax.swing.JButton();
        txt_maphieu = new javax.swing.JLabel();
        bttraphong = new javax.swing.JButton();
        btnhanphong = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_timkiem = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));

        txt_userkh.setEditable(false);
        txt_userkh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_userkh.setText("user1");
        txt_userkh.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 204), null));
        txt_userkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userkhActionPerformed(evt);
            }
        });

        txt_datet.setEditable(false);
        txt_datet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_datet.setText("dd/mm/yyyy");
        txt_datet.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 204), null));

        txt_ndate.setEditable(false);
        txt_ndate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ndate.setText("1");
        txt_ndate.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 204), null));

        txt_room.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_room.setModel(new javax.swing.DefaultComboBoxModel<>( listphongtrong));
        txt_room.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 204), null));
        txt_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_roomActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã Phiếu:");

        jLabel2.setText("Mã Khách hàng");

        jLabel4.setText("Ngày thuê");

        jLabel5.setText("Số ngày thuê");

        txt_namekh.setEditable(false);
        txt_namekh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_namekh.setText("abc");
        txt_namekh.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 204), null));

        txt_old.setEditable(false);
        txt_old.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_old.setText("18");
        txt_old.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 204), null));

        txt_sdt.setEditable(false);
        txt_sdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_sdt.setText("0123456789");
        txt_sdt.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 204), null));

        txt_email.setEditable(false);
        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_email.setText("abc@gmail.com");
        txt_email.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 204), null));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        txt_cmnd.setEditable(false);
        txt_cmnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_cmnd.setText("123456789123");
        txt_cmnd.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 204), null));
        txt_cmnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cmndActionPerformed(evt);
            }
        });

        jLabel7.setText("Tên KH");

        jLabel8.setText("Tuổi");

        txt_gt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_gt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác"}));
        txt_gt.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 204), null));

        jLabel9.setText("Giới tính");

        jLabel10.setText("SĐT");

        jLabel11.setText("Số CMND/CCCD");

        jLabel12.setText("Email");

        jLabel3.setText("Chọn phòng");

        txt_ttang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang Chờ", "Đã nhận phòng", "Đã hoàn thành", "Đã hủy" }));
        txt_ttang.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 204), null));
        txt_ttang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ttangActionPerformed(evt);
            }
        });

        jLabel6.setText("TÌnh trạng phiếu");

        bt_save.setText("Lưu");
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });

        bt_delete1.setBackground(new java.awt.Color(255, 102, 102));
        bt_delete1.setForeground(new java.awt.Color(102, 255, 255));
        bt_delete1.setText("Xóa phiếu");
        bt_delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_delete1ActionPerformed(evt);
            }
        });

        txt_maphieu.setText("...");

        bttraphong.setBackground(new java.awt.Color(255, 255, 153));
        bttraphong.setText("Trả Phòng");
        bttraphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttraphongActionPerformed(evt);
            }
        });

        btnhanphong.setBackground(new java.awt.Color(153, 255, 153));
        btnhanphong.setText("Nhận Phòng");
        btnhanphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhanphongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ttang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_room, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnhanphong, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_userkh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ndate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_namekh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_datet, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_maphieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_cmnd)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_gt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_old, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(bttraphong, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(bt_save, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_delete1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txt_maphieu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_userkh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_datet)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ndate)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_namekh)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_old)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_gt)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sdt)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cmnd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_room))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ttang)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhanphong, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttraphong, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_save, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        txt_timkiem.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_timkiemAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icon/icons8_Search_Contacts_40px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setAutoscrolls(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu", "TK khách hàng", "Ngày thuê", "Số ngày thuê", "Mã Phòng", "Tình trạng", "Tên Khách Hàng", "Tuổi", "Giới tính", "SĐT", "Email", "CMND/CCCD"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 235, 249));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
      

      
    }  
    private void txt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemActionPerformed

    private void bt_delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_delete1ActionPerformed
        // TODO add your handling code here:
        
        if(DAO.DAO_PDP.xoaphieu(txt_maphieu.getText())!=-1)
        {
            thongbao.thongbao("Xóa thành công!", "Thông báo");
        }
        else
        {
             thongbao.thongbao("Xóa thất bại!", "Thông báo");
        }
         BLL.BLL_dodulieu_PDP.dodulieu(jTable1);
    }//GEN-LAST:event_bt_delete1ActionPerformed

    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed
        // TODO add your handling code here:
        DTO.DTO_PHdatphong pp =new DTO_PHdatphong();
        pp.setIdphong((String) txt_room.getSelectedItem());
        pp.setTinhtrang((String) txt_ttang.getSelectedItem());
        pp.setNgaythue(BLL.ChuyenDoi.GetDate(txt_datet.getText()));
        pp.setIdphieu(txt_maphieu.getText());
        pp.setSongaythue(Integer.parseInt(txt_ndate.getText()));
        if(DAO.DAO_PDP.setdata(pp)!=-1)
        {
            thongbao.thongbao("thành công", "thông báo");
        }else{
             thongbao.thongbao("thất bại", "thông báo");
            
        }
        BLL.BLL_dodulieu_PDP.dodulieu(jTable1);
        
        
    }//GEN-LAST:event_bt_saveActionPerformed

    private void txt_ttangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ttangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ttangActionPerformed

    private void txt_cmndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cmndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cmndActionPerformed

    private void txt_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_roomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_roomActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_userkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userkhActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        setListphongtrong(""); 
         txt_room.setModel(new javax.swing.DefaultComboBoxModel<>( listphongtrong));
         btnhanphong.setVisible(false);
         bttraphong.setVisible(false);
        int sl = jTable1.getSelectedRowCount();
        int vitri=jTable1.getSelectedRow();
       
        if (sl == 1) {
            txt_maphieu.setText((String) jTable1.getValueAt(vitri, 0));
            
            txt_userkh.setText((String) jTable1.getValueAt(vitri, 1));
            txt_datet.setText((String) jTable1.getValueAt(vitri, 2));
            txt_ndate.setText((String) jTable1.getValueAt(vitri, 3));
            txt_namekh.setText((String) jTable1.getValueAt(vitri, 6));
            txt_old.setText((String) jTable1.getValueAt(vitri, 7));
            txt_gt.setSelectedItem(jTable1.getValueAt(vitri, 8));
            txt_sdt.setText((String) jTable1.getValueAt(vitri, 9));
            txt_email.setText((String) jTable1.getValueAt(vitri, 10));
            txt_cmnd.setText((String) jTable1.getValueAt(vitri, 11));
            txt_room.setSelectedItem(jTable1.getValueAt(vitri, 4));
            txt_ttang.setSelectedItem(jTable1.getValueAt(vitri, 5));
            if(jTable1.getValueAt(vitri, 5).equals("Đang Chờ"))
            {
               btnhanphong.setVisible(true);
                setListphongtrong("Trống"); 
                txt_room.setModel(new javax.swing.DefaultComboBoxModel<>( listphongtrong));
            }
            if(jTable1.getValueAt(vitri, 5).equals("Đã nhận phòng"))
            {
                bttraphong.setVisible(true);
                
            }
            
        
        }
        else{
            
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void btnhanphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhanphongActionPerformed
        // thay đôi tình trạn thành đã nhận thay đổi ngày đặt thành hôm nay +chọn phòng
       
         
        DTO.DTO_PHdatphong pp =new DTO_PHdatphong();
        pp.setIdphong((String) txt_room.getSelectedItem());
        pp.setTinhtrang("Đã nhận phòng");
        pp.setNgaythue(BLL.BLL_PDP.getDate());
        pp.setIdphieu(txt_maphieu.getText());
        pp.setSongaythue(Integer.parseInt(txt_ndate.getText()));
        if(pp.getIdphong()==null)
        {
            thongbao.thongbao("Vui lòng chọn phòng","Thông Báo");
        }
        else
        if(DAO.DAO_PDP.setdata(pp)!=-1)
        {
            thongbao.thongbao("thành công", "thông báo");
            DAO.DAO_phong.suattphong(pp, "Đang sử dụng");
        }else{
             thongbao.thongbao("thất bại", "thông báo");
            
        }
        BLL.BLL_dodulieu_PDP.dodulieu(jTable1);
       
    }//GEN-LAST:event_btnhanphongActionPerformed

    private void bttraphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttraphongActionPerformed
          
        
         DTO.DTO_PHdatphong pp =new DTO_PHdatphong();
        pp.setIdphong((String) txt_room.getSelectedItem());
        pp.setTinhtrang("Đã hoàn thành");
        pp.setNgaythue(BLL.ChuyenDoi.GetDate(txt_datet.getText()));
        pp.setIdphieu(txt_maphieu.getText());
        int d=BLL.BLL_PDP.getDate().getDate()-BLL.ChuyenDoi.GetDate(txt_datet.getText()).getDate()+1;
     
        pp.setSongaythue(d);
        if(DAO.DAO_PDP.setdata(pp)!=-1)
        {
            thongbao.thongbao("thành công", "thông báo");
            DAO.DAO_phong.suattphong(pp, "Trống");
        }else{
             thongbao.thongbao("thất bại", "thông báo");
            
        }
       
        BLL.BLL_dodulieu_PDP.dodulieu(jTable1);
    }//GEN-LAST:event_bttraphongActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           String txtString=txt_timkiem.getText().trim();
           if(txtString.length()==0)
           {
               sorter.setRowFilter(null);
           }
           else{
               try {
                  sorter.setRowFilter(RowFilter.regexFilter(txtString));
               } catch(PatternSyntaxException pse) {
                     System.out.println("Bad regex pattern");
               }
           }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_timkiemAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_timkiemAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_timkiemAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_QLphieuDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_QLphieuDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_QLphieuDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_QLphieuDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_QLphieuDP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_delete1;
    private javax.swing.JButton bt_save;
    private javax.swing.JButton btnhanphong;
    private javax.swing.JButton bttraphong;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_cmnd;
    private javax.swing.JTextField txt_datet;
    private javax.swing.JTextField txt_email;
    private javax.swing.JComboBox<String> txt_gt;
    private javax.swing.JLabel txt_maphieu;
    private javax.swing.JTextField txt_namekh;
    private javax.swing.JTextField txt_ndate;
    private javax.swing.JTextField txt_old;
    private javax.swing.JComboBox<String> txt_room;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_timkiem;
    private javax.swing.JComboBox<String> txt_ttang;
    private javax.swing.JTextField txt_userkh;
    // End of variables declaration//GEN-END:variables
}
